Revamp native-image build tooling, fix UTF-8 encoding issue.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -11,6 +11,39 @@ if [[ $1 = clean ]]; then
 elif [[ $1 = hiera ]]; then
     shift
     exec clojure -X:hiera "$@"
+
+elif [[ $1 = native-image ]]; then
+    shift
+    GRAAL_ROOT="${GRAAL_ROOT:-$HOME/.local/share/graalvm}"
+
+    # Look for GraalVM location if not set ahead of time
+    if [[ -z $GRAAL_HOME ]]; then
+        if [[ ! -d $GRAAL_ROOT ]]; then
+            echo "GRAAL_ROOT is not a valid directory: $GRAAL_ROOT" >&2
+            exit 2
+        fi
+        GRAAL_HOME="$(for dir in "$GRAAL_ROOT"/graalvm-*; do echo "$dir"; done | sort | tail -n 1)"
+        # Special case for the MacOS version
+        if [[ -n $GRAAL_HOME && -d "${GRAAL_HOME}/Contents/Home" ]]; then
+            GRAAL_HOME="${GRAAL_HOME}/Contents/Home"
+        fi
+    fi
+
+    # Make sure we found something to use
+    if [[ -z $GRAAL_HOME || ! -d $GRAAL_HOME ]]; then
+        echo "GraalVM directory not found under $GRAAL_ROOT" >&2
+        echo "Download from https://github.com/graalvm/graalvm-ce-builds/releases and and extract there" >&2
+        echo "Alternately, set GRAAL_HOME pointing at the install directory" >&2
+        exit 2
+    fi
+
+    # Switch to GraalVM SDK
+    echo "Using GraalVM from $GRAAL_HOME"
+    export JAVA_HOME="${GRAAL_HOME}"
+    export PATH="${JAVA_HOME}/bin:${PATH}"
+
+    exec clojure -T:build native-image "$@"
+
 elif [[ $1 = deploy ]]; then
     shift
     if [[ -z $CLOJARS_USERNAME && -z $CLOJARS_PASSWORD && -f $HOME/.clojure/clojars.env ]]; then
diff --git a/bin/package b/bin/package
--- a/bin/package
+++ b/bin/package
@@ -5,12 +5,13 @@ set -e
 
 cd "$(dirname "${BASH_SOURCE[0]}")/.."
 
+DIST_FORCE=false
 DIST_CLEAN=false
 DIST_TARGET=all
 
 
 usage() {
-    echo "bin/package [--clean] [--target TARGET]" >&2
+    echo "bin/package [--clean] [--force] [--target TARGET]" >&2
     echo >&2
     echo "Targets: jar, macos, linux, linux-static" >&2
 }
@@ -26,6 +27,10 @@ while [[ $# -gt 0 ]]; do
             DIST_CLEAN=true
             shift
             ;;
+        --force)
+            DIST_FORCE=true
+            shift
+            ;;
         --target)
             DIST_TARGET="$2"
             shift
@@ -39,12 +44,32 @@ while [[ $# -gt 0 ]]; do
 done
 
 
-CLJSTYLE_VERSION="$(clojure -T:build print-version | cut -d ' ' -f 2)"
-# TODO: check that we're on main branch
-# TODO: check for dirty git state?
-# TODO: check that VERSION.txt matches?
+readonly CLJSTYLE_VERSION="$(clojure -T:build print-version | cut -d ' ' -f 2)"
+readonly GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+readonly GIT_STATUS="$(git status --porcelain --untracked-files=no)"
 
-echo "Preparing full release distribution for $CLJSTYLE_VERSION"
+if [[ $GIT_BRANCH != main ]]; then
+    if [[ $DIST_FORCE != true ]]; then
+        echo -e "\033[0;31mAborting packaging from non-main branch $GIT_BRANCH\033[0m" >&2
+        exit 1
+    else
+        echo -e "\033[0;31mWARNING: packaging from non-main branch $GIT_BRANCH\033[0m" >&2
+    fi
+fi
+
+if [[ -n $GIT_STATUS ]]; then
+    if [[ $DIST_FORCE != true ]]; then
+        echo -e "\033[0;31mAborting packaging with uncommitted changes:\033[0m" >&2
+        echo "$GIT_STATUS" >&2
+        exit 1
+    else
+        echo -e "\033[0;31mWARNING: packaging with uncommitted changes:\033[0m" >&2
+        echo "$GIT_STATUS" >&2
+    fi
+fi
+
+
+echo "Preparing release distribution for $CLJSTYLE_VERSION"
 
 if [[ $DIST_CLEAN == true ]]; then
   rm -rf dist target
@@ -100,8 +125,11 @@ if [[ $DIST_TARGET == all || $DIST_TARGET == linux ]]; then
         echo "Building Linux binary"
         rm -rf target/dist/linux
         mkdir -p target/dist/linux
-        docker build -t "cljstyle-builder:$CLJSTYLE_VERSION" .
-        DOCKER_CONTAINER_ID=$(docker create "cljstyle-builder:$CLJSTYLE_VERSION")
+        docker build \
+            --platform linux/amd64 \
+            -t "cljstyle-builder:$CLJSTYLE_VERSION" \
+            .
+        DOCKER_CONTAINER_ID=$(docker create --platform linux/amd64 "cljstyle-builder:$CLJSTYLE_VERSION")
         docker cp "${DOCKER_CONTAINER_ID}:/usr/local/bin/cljstyle" target/dist/linux/cljstyle
         docker container rm "$DOCKER_CONTAINER_ID"
         if [[ ! -f target/dist/linux/cljstyle ]]; then
@@ -124,8 +152,12 @@ if [[ $DIST_TARGET == all || $DIST_TARGET == linux-static ]]; then
         echo "Building Linux static binary"
         rm -rf target/dist/linux-static
         mkdir -p target/dist/linux-static
-        docker build --build-arg GRAAL_STATIC=true -t "cljstyle-static-builder:$CLJSTYLE_VERSION" .
-        DOCKER_CONTAINER_ID=$(docker create "cljstyle-static-builder:$CLJSTYLE_VERSION")
+        docker build \
+            --platform linux/amd64 \
+            --build-arg GRAAL_STATIC=true \
+            -t "cljstyle-static-builder:$CLJSTYLE_VERSION" \
+            .
+        DOCKER_CONTAINER_ID=$(docker create --platform linux/amd64 "cljstyle-static-builder:$CLJSTYLE_VERSION")
         docker cp "${DOCKER_CONTAINER_ID}:/usr/local/bin/cljstyle" target/dist/linux-static/cljstyle
         docker container rm "$DOCKER_CONTAINER_ID"
         if [[ ! -f target/dist/linux-static/cljstyle ]]; then
