Add --static option to install script.

diff --git a/util/install-cljstyle b/util/install-cljstyle
--- a/util/install-cljstyle
+++ b/util/install-cljstyle
@@ -11,6 +11,7 @@ install_dir=$default_install_dir
 default_download_dir="/tmp"
 download_dir=$default_download_dir
 version=""
+modifier=""
 
 case "$(uname -s)" in
     Linux*)  platform=linux ;;
@@ -26,7 +27,7 @@ print_help() {
     echo "Installs latest version of cljstyle."
     echo -e
     echo "Usage:"
-    echo "install [--dir <dir>] [--download-dir <download-dir>] [--arch <architecture>] [--version <version>]"
+    echo "install [--dir <dir>] [--download-dir <download-dir>] [--arch <architecture>] [--version <version>] [--static]"
     echo -e
     echo "Defaults:"
     echo " * Installation directory: ${default_install_dir}"
@@ -41,7 +42,8 @@ do
     if [[ $key == --help ]]; then
         print_help
         exit
-    elif [[ -z "${2:-}" ]]; then
+    elif [[ -z "${2:-}" && $key != --static ]]; then
+        echo "Missing option value" >&2
         print_help
         exit 1
     fi
@@ -62,6 +64,10 @@ do
             shift
             shift
             ;;
+        --static)
+            modifier="_static"
+            shift
+            ;;
         --version|--release-version)
             version="$2"
             shift
@@ -78,7 +84,7 @@ if [[ "$version" == "" ]]; then
   version="$(curl -s https://raw.githubusercontent.com/greglook/cljstyle/main/VERSION.txt)"
 fi
 
-archive_file="cljstyle_${version}_${platform}_${architecture}.zip"
+archive_file="cljstyle_${version}_${platform}_${architecture}${modifier}.zip"
 download_url="https://github.com/greglook/cljstyle/releases/download/${version}/${archive_file}"
 
 mkdir -p "$download_dir"
